### ISSUE TITLE
Is there a way to reduce the transparency of the application menu bar?

### ISSUE THREAD

**Issue by dlivxpr** [yeyushengfan258/Inverse-kde#3]
If you are in a pure white application, the system tray on the right side of the application menu bar cannot see the words clearly. Like in the picture.
![Screenshot_20201116_221131](https://user-images.githubusercontent.com/34794522/99266004-4931c480-285d-11eb-8728-d067a3eb6b83.png)

**Comment by dlivxpr** [comment]
The simple menu is also too transparent to read the words clearly
![Screenshot_20201116_224547](https://user-images.githubusercontent.com/34794522/99266217-8007da80-285d-11eb-8975-2e0167173585.png)

**Comment by yeyushengfan258** [comment]
你可以先用下我同名dark的那套,或我其他的主题.
小米这套我很久没更新了,目前解决的方法是再做套alt版本的解决看不清字的问题,或者你说的模糊或者颜色问题.
等我抽时间来更新小米的主题吧.

**Comment by dlivxpr** [comment]
好的，现在正在用着同名的dark主题，这个小米的主题配上小米笔记本非常好看
